# This workflow will build the extension jar and retain the artifact.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

 name: Build jar

 on: [workflow_dispatch]

 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - name: Set up JDK
       uses: actions/setup-java@v4
       with:
         java-version: '21'
         distribution: 'temurin'
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
     - name: Build with Gradle
       run: ./gradlew shadowJar -P toolchain=21
     - uses: actions/upload-artifact@v2
       with:
         name: libs
         path: build/libs
         retention-days: 1
